language: php

matrix:
  include:
    - php: 5.5
      env: deps=low
    - php: 5.6
      env: deps=low
    - php: hhvm
      env: deps=low
    - php: 7.0
      env: deps=low
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: 7.0
  fast_finish: true

install:
  - if [ "$deps" = "no" ]; then composer --prefer-stable update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=strict

script:
  phpunit

sudo: false

cache:
  directories:
    - node_modules
    - vendor
    - bower_components

webhooks:
  urls:
    - https://webhooks.gitter.im/e/31edf9087439c96470f5
  on_success: change
  on_failure: always
  on_start: false
