build: false
clone_depth: 10
platform: x64
clone_folder: c:\projects\guzzle-bundle

cache:
    - c:\php -> appveyor.yml

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET SYMFONY_DEPRECATIONS_HELPER=strict
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
    - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
    - cd c:\php
    - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.1.5-Win32-VC14-x64.zip
    - IF %PHP%==1 7z x php-7.1.5-Win32-VC14-x64.zip -y >nul
    - IF %PHP%==1 del /Q *.zip
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - IF %PHP%==1 copy /Y php.ini-development php.ini
    - IF %PHP%==1 echo max_execution_time=1200 >> php.ini
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd c:\projects\guzzle-bundle
    - composer install --prefer-dist

test_script:
    - cd c:\projects\guzzle-bundle
    - vendor\bin\phpunit.bat

branches:
    only:
        - master
        - 1.3
